<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_DEBUG' => '0',
  'APP_SECRET' => 'f08d9bf2f0fff4e7544cfa88012c0849',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/data/data.db',
);
